### ISSUE TITLE
Could not resolve placeholder 'swagger.publish.security-token' in string value "${swagger.publish.security-token}" 

### ISSUE THREAD

**Issue by mengxu2018** [burnettzhong/parliament#6]
我按照文档部署之后，我发现这个错误，
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.5.RELEASE:run (default-cli) on project account-service: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'com.keyholesoftware.publish.swagger.EnablePublishSwaggerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.keyholesoftware.publish.swagger.EnablePublishSwaggerConfiguration.securityToken; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'swagger.publish.security-token' in string value "${swagger.publish.security-token}" -> [Help 1]

**Comment by mengxu2018** [comment]
我知道可以设置这个value
swagger:
  publish:
    security-token: 9a019713-XXXX-XXXX-XXXX-74090a0ea9f7
但是这个token值应该设置成什么在文档里面并没有说明，我随便设置一个又会报另外http response的错误

**Comment by MicroCreativity** [comment]
我也碰到了同样的问题....，怎么解决的？

**Comment by MicroCreativity** [comment]
![image](https://user-images.githubusercontent.com/18007558/47961506-56e5ca00-e047-11e8-9505-0f323e454b29.png)

根本用不了....，看了源码，是操作mongodb的问题，作者也不解决一下这个问题...

**Comment by burnettzhong** [comment]
Mongodb的问题已经解决

**Comment by burnettzhong** [comment]
> 我知道可以设置这个value
> swagger:
> publish:
> security-token: 9a019713-XXXX-XXXX-XXXX-74090a0ea9f7
> 但是这个token值应该设置成什么在文档里面并没有说明，我随便设置一个又会报另外http response的错误

这个security token暂时没有启用，不用生成。以后如果考虑安全问题，可以使用其他方式加密。
